---
spring:
  profiles: dev  
message:
  admin: message from admin cloud dev 1
  user:  message from user cloud dev 1
  
---
spring:
  profiles: prod
message:
  admin: message from admin cloud prod
  user:  message from admin cloud specific prod