---
spring:
  profiles: dev  
message:
  admin: message from admin cloud dev 6
  user:  message from user cloud dev 6
  
---
spring:
  profiles: prod
message:
  admin: message from admin cloud prod
  user:  message from admin cloud specific prod