---
spring:
  profiles: dev  
message:
  admin: message from admin cloud app specific dev 2
  user:  message from user cloud app specific dev 2
  
---

spring:
  profiles: prod
message:
  admin: message from admin cloud app specific prod
  user:  message from user cloud app specific prod